# Generated by Django 6.0 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(blank=True, max_length=25, null=True, unique=True, verbose_name='shortened url'),
        ),
    ]
