# Generated by Django 6.0 on 2025-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='slug',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
