# Generated by Django 6.0 on 2025-12-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_url_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
