# Generated by Django 6.0 on 2025-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_rename_updated_url_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
