# Generated by Django 6.0 on 2025-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_alter_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
